/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindingResponse } from '../../models/finding-response';

export interface FindingsList$Plain$Params {
  caseId: string;
}

export function findingsList$Plain(http: HttpClient, rootUrl: string, params: FindingsList$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FindingResponse>>> {
  const rb = new RequestBuilder(rootUrl, findingsList$Plain.PATH, 'get');
  if (params) {
    rb.path('caseId', params.caseId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FindingResponse>>;
    })
  );
}

findingsList$Plain.PATH = '/api/cases/{caseId}/findings';
