/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateFindingRequest } from '../../models/create-finding-request';
import { FindingResponse } from '../../models/finding-response';

export interface FindingsCreate$Json$Params {
  caseId: string;
      body?: CreateFindingRequest
}

export function findingsCreate$Json(http: HttpClient, rootUrl: string, params: FindingsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FindingResponse>> {
  const rb = new RequestBuilder(rootUrl, findingsCreate$Json.PATH, 'post');
  if (params) {
    rb.path('caseId', params.caseId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FindingResponse>;
    })
  );
}

findingsCreate$Json.PATH = '/api/cases/{caseId}/findings';
