/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CaseResponse } from '../../models/case-response';
import { CreateCaseRequest } from '../../models/create-case-request';

export interface CasesCreate$Plain$Params {
      body?: CreateCaseRequest
}

export function casesCreate$Plain(http: HttpClient, rootUrl: string, params?: CasesCreate$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CaseResponse>> {
  const rb = new RequestBuilder(rootUrl, casesCreate$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CaseResponse>;
    })
  );
}

casesCreate$Plain.PATH = '/api/cases';
