/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CaseResponse } from '../../models/case-response';

export interface CasesMarkExtracted$Plain$Params {
  id: string;
}

export function casesMarkExtracted$Plain(http: HttpClient, rootUrl: string, params: CasesMarkExtracted$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CaseResponse>> {
  const rb = new RequestBuilder(rootUrl, casesMarkExtracted$Plain.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CaseResponse>;
    })
  );
}

casesMarkExtracted$Plain.PATH = '/api/cases/{id}/extract';
