/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CaseResponse } from '../../models/case-response';

export interface CasesList$Json$Params {
}

export function casesList$Json(http: HttpClient, rootUrl: string, params?: CasesList$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CaseResponse>>> {
  const rb = new RequestBuilder(rootUrl, casesList$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CaseResponse>>;
    })
  );
}

casesList$Json.PATH = '/api/cases';
