/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExtractedFieldResponse } from '../../models/extracted-field-response';

export interface ExtractedFieldsList$Json$Params {
  documentId: string;
}

export function extractedFieldsList$Json(http: HttpClient, rootUrl: string, params: ExtractedFieldsList$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExtractedFieldResponse>>> {
  const rb = new RequestBuilder(rootUrl, extractedFieldsList$Json.PATH, 'get');
  if (params) {
    rb.path('documentId', params.documentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExtractedFieldResponse>>;
    })
  );
}

extractedFieldsList$Json.PATH = '/api/documents/{documentId}/extracted-fields';
