/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateExtractedFieldsRequest } from '../../models/create-extracted-fields-request';
import { ExtractedFieldResponse } from '../../models/extracted-field-response';

export interface ExtractedFieldsCreate$Json$Params {
  documentId: string;
      body?: CreateExtractedFieldsRequest
}

export function extractedFieldsCreate$Json(http: HttpClient, rootUrl: string, params: ExtractedFieldsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExtractedFieldResponse>>> {
  const rb = new RequestBuilder(rootUrl, extractedFieldsCreate$Json.PATH, 'post');
  if (params) {
    rb.path('documentId', params.documentId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExtractedFieldResponse>>;
    })
  );
}

extractedFieldsCreate$Json.PATH = '/api/documents/{documentId}/extracted-fields';
