/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuditEventResponse } from '../../models/audit-event-response';

export interface AuditEventsList$Plain$Params {
  caseId: string;
}

export function auditEventsList$Plain(http: HttpClient, rootUrl: string, params: AuditEventsList$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AuditEventResponse>>> {
  const rb = new RequestBuilder(rootUrl, auditEventsList$Plain.PATH, 'get');
  if (params) {
    rb.path('caseId', params.caseId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AuditEventResponse>>;
    })
  );
}

auditEventsList$Plain.PATH = '/api/cases/{caseId}/audit-events';
