/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AiReviewResponse } from '../../models/ai-review-response';
import { CreateAiReviewRequest } from '../../models/create-ai-review-request';

export interface AiReviewsCreate$Plain$Params {
  caseId: string;
      body?: CreateAiReviewRequest
}

export function aiReviewsCreate$Plain(http: HttpClient, rootUrl: string, params: AiReviewsCreate$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<AiReviewResponse>> {
  const rb = new RequestBuilder(rootUrl, aiReviewsCreate$Plain.PATH, 'post');
  if (params) {
    rb.path('caseId', params.caseId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AiReviewResponse>;
    })
  );
}

aiReviewsCreate$Plain.PATH = '/api/cases/{caseId}/ai-reviews';
