/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AiReviewResponse } from '../../models/ai-review-response';

export interface AiReviewsList$Json$Params {
  caseId: string;
}

export function aiReviewsList$Json(http: HttpClient, rootUrl: string, params: AiReviewsList$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AiReviewResponse>>> {
  const rb = new RequestBuilder(rootUrl, aiReviewsList$Json.PATH, 'get');
  if (params) {
    rb.path('caseId', params.caseId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AiReviewResponse>>;
    })
  );
}

aiReviewsList$Json.PATH = '/api/cases/{caseId}/ai-reviews';
