/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeResponse } from '../../models/me-response';

export interface MeGet$Plain$Params {
}

export function meGet$Plain(http: HttpClient, rootUrl: string, params?: MeGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<MeResponse>> {
  const rb = new RequestBuilder(rootUrl, meGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MeResponse>;
    })
  );
}

meGet$Plain.PATH = '/api/me';
