/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnqueuePipelineJobRequest } from '../../models/enqueue-pipeline-job-request';
import { PipelineJobResponse } from '../../models/pipeline-job-response';

export interface PipelineJobsEnqueue$Json$Params {
  caseId: string;
  'Idempotency-Key': string;
      body?: EnqueuePipelineJobRequest
}

export function pipelineJobsEnqueue$Json(http: HttpClient, rootUrl: string, params: PipelineJobsEnqueue$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PipelineJobResponse>> {
  const rb = new RequestBuilder(rootUrl, pipelineJobsEnqueue$Json.PATH, 'post');
  if (params) {
    rb.path('caseId', params.caseId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PipelineJobResponse>;
    })
  );
}

pipelineJobsEnqueue$Json.PATH = '/api/cases/{caseId}/pipeline-jobs';
