/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AiReviewInputResponse } from '../../models/ai-review-input-response';

export interface AiReviewInputGet$Json$Params {
  caseId: string;
}

export function aiReviewInputGet$Json(http: HttpClient, rootUrl: string, params: AiReviewInputGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<AiReviewInputResponse>> {
  const rb = new RequestBuilder(rootUrl, aiReviewInputGet$Json.PATH, 'get');
  if (params) {
    rb.path('caseId', params.caseId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AiReviewInputResponse>;
    })
  );
}

aiReviewInputGet$Json.PATH = '/api/cases/{caseId}/ai-review-input';
