namespace CaseAuth.Api.Entities;

// RowVersion is an app-managed concurrency token (regenerated by CaseAuthDbContext on every
// update), not a database-native rowversion column: SQLite has no equivalent to SQL Server's
// `rowversion`, and this scheme works unchanged on Postgres too.
public class Case
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public required string FirmId { get; set; }

    public Guid ApplicantId { get; set; }
    public Applicant? Applicant { get; set; }

    public CaseStatus Status { get; set; } = CaseStatus.Draft;

    public required string CreatedByUserId { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    public Guid RowVersion { get; set; } = Guid.NewGuid();

    public List<Document> Documents { get; set; } = [];
    public List<Finding> Findings { get; set; } = [];
    public List<AiReview> AiReviews { get; set; } = [];
    public List<Decision> Decisions { get; set; } = [];
}
