/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingSeverity } from '../models/finding-severity';
export interface AiReviewInputFindingResponse {
  code?: string | null;
  id?: string;
  message?: string | null;
  score?: number | null;
  severity?: FindingSeverity;
  sourceFieldIds?: Array<string> | null;
}
