/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AiRecommendation } from './ai-recommendation';

/**
 * Each possible value of `AiRecommendation`
 */
export const AI_RECOMMENDATION: AiRecommendation[] = [
  'Approve',
  'Reject',
  'Escalate'
];