/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AiReviewInputFieldResponse } from '../models/ai-review-input-field-response';
import { AiReviewInputFindingResponse } from '../models/ai-review-input-finding-response';
export interface AiReviewInputResponse {
  caseId?: string;
  fields?: Array<AiReviewInputFieldResponse> | null;
  findings?: Array<AiReviewInputFindingResponse> | null;
}
