/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AiRecommendation } from '../models/ai-recommendation';
export interface AiReviewResponse {
  createdAt?: string;
  id?: string;
  modelName?: string | null;
  modelVersion?: string | null;
  rationale?: string | null;
  recommendation?: AiRecommendation;
  version?: number;
}
