/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicantKind } from './applicant-kind';

/**
 * Each possible value of `ApplicantKind`
 */
export const APPLICANT_KIND: ApplicantKind[] = [
  'Individual',
  'Entity'
];