/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditOutcome } from './audit-outcome';

/**
 * Each possible value of `AuditOutcome`
 */
export const AUDIT_OUTCOME: AuditOutcome[] = [
  'Success',
  'Rejected',
  'Failure'
];