/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditOutcome } from '../models/audit-outcome';
export interface AuditEventResponse {
  action?: string | null;
  actorUsername?: string | null;
  aiReviewVersion?: number | null;
  caseId?: string | null;
  correlationId?: string | null;
  id?: string;
  outcome?: AuditOutcome;
  timestamp?: string;
}
