/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CaseStatus } from './case-status';

/**
 * Each possible value of `CaseStatus`
 */
export const CASE_STATUS: CaseStatus[] = [
  'Draft',
  'Submitted',
  'UnderReview',
  'PendingDecision',
  'Approved',
  'Rejected',
  'Withdrawn'
];