/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type CaseStatus = 'Uploaded' | 'Extracted' | 'Screened' | 'AiReviewed' | 'AwaitingDecision' | 'Approved' | 'Rejected' | 'Escalated';

