/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExtractedFieldInput } from '../models/extracted-field-input';
export interface CreateExtractedFieldsRequest {
  fields?: Array<ExtractedFieldInput> | null;
}
