/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AiRecommendation } from '../models/ai-recommendation';
export interface CreateAiReviewRequest {
  modelName?: string | null;
  modelVersion?: string | null;
  rationale?: string | null;
  recommendation?: AiRecommendation;
}
