/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCaseRequest {
  applicantDateOfBirth?: string | null;
  applicantEmail?: string | null;
  applicantFullName?: string | null;
  applicantPhone?: string | null;
}
