/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DecisionOutcome } from '../models/decision-outcome';
export interface CreateDecisionRequest {
  aiReviewId?: string | null;
  outcome?: DecisionOutcome;
}
