/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicantKind } from '../models/applicant-kind';
export interface CreateCaseRequest {
  applicantDateOfBirth?: string | null;
  applicantEmail?: string | null;
  applicantFullName?: string | null;
  applicantKind?: ApplicantKind;
  applicantPhone?: string | null;
}
