/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DecisionOutcome } from '../models/decision-outcome';
export interface DecisionResponse {
  aiReviewId?: string | null;
  caseId?: string;
  decidedAt?: string;
  decidedByUserId?: string | null;
  id?: string;
  outcome?: DecisionOutcome;
}
