/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DecisionOutcome } from './decision-outcome';

/**
 * Each possible value of `DecisionOutcome`
 */
export const DECISION_OUTCOME: DecisionOutcome[] = [
  'Approved',
  'Rejected',
  'Escalated'
];