/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from '../models/document-type';
export interface DocumentResponse {
  contentType?: string | null;
  documentType?: DocumentType;
  fileName?: string | null;
  id?: string;
  sizeBytes?: number;
  uploadedAt?: string;
  uploadedByUserId?: string | null;
}
