/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PipelineJobType } from '../models/pipeline-job-type';
export interface EnqueuePipelineJobRequest {
  jobType?: PipelineJobType;
}
