/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExtractedFieldInput {
  confidence?: number | null;
  fieldName?: string | null;
  fieldValue?: string | null;
}
