/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingSeverity } from './finding-severity';

/**
 * Each possible value of `FindingSeverity`
 */
export const FINDING_SEVERITY: FindingSeverity[] = [
  'Low',
  'Medium',
  'High'
];