/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingSeverity } from '../models/finding-severity';
import { FindingSource } from '../models/finding-source';
export interface FindingResponse {
  code?: string | null;
  createdAt?: string;
  id?: string;
  message?: string | null;
  severity?: FindingSeverity;
  source?: FindingSource;
}
