/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeResponse {
  firmId?: string | null;
  role?: string | null;
  userId?: string | null;
  username?: string | null;
}
