/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PipelineJobStatus } from '../models/pipeline-job-status';
import { PipelineJobType } from '../models/pipeline-job-type';
export interface PipelineJobResponse {
  attempts?: number;
  caseId?: string;
  completedAt?: string | null;
  createdAt?: string;
  error?: string | null;
  id?: string;
  jobType?: PipelineJobType;
  startedAt?: string | null;
  status?: PipelineJobStatus;
}
