/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PipelineJobType } from './pipeline-job-type';

/**
 * Each possible value of `PipelineJobType`
 */
export const PIPELINE_JOB_TYPE: PipelineJobType[] = [
  'Extract',
  'Screen',
  'AiReview'
];