/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PipelineJobStatus } from './pipeline-job-status';

/**
 * Each possible value of `PipelineJobStatus`
 */
export const PIPELINE_JOB_STATUS: PipelineJobStatus[] = [
  'Pending',
  'Processing',
  'Completed',
  'Failed'
];