/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDecisionRequest } from '../../models/create-decision-request';
import { DecisionResponse } from '../../models/decision-response';

export interface DecisionsCreate$Json$Params {
  caseId: string;
  'Idempotency-Key'?: string;
  'If-Match'?: string;
      body?: CreateDecisionRequest
}

export function decisionsCreate$Json(http: HttpClient, rootUrl: string, params: DecisionsCreate$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DecisionResponse>> {
  const rb = new RequestBuilder(rootUrl, decisionsCreate$Json.PATH, 'post');
  if (params) {
    rb.path('caseId', params.caseId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DecisionResponse>;
    })
  );
}

decisionsCreate$Json.PATH = '/api/cases/{caseId}/decisions';
